// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJY_ONMjam_W6Yofc76KnI2j_BQwZ5Zuo',
    appId: '1:605845063930:web:dec9e3b4886e0299316143',
    messagingSenderId: '605845063930',
    projectId: 'luxe-ecom-a5022',
    authDomain: 'luxe-ecom-a5022.firebaseapp.com',
    storageBucket: 'luxe-ecom-a5022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa4e9alr4sLnUruAUP4lfoKFNmFicMsQk',
    appId: '1:605845063930:android:5403cd2a3b19f910316143',
    messagingSenderId: '605845063930',
    projectId: 'luxe-ecom-a5022',
    storageBucket: 'luxe-ecom-a5022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGxV5YtIlTU29t9d-XgqaCZB8km8mIf7U',
    appId: '1:605845063930:ios:55ce97a10a9d9e2d316143',
    messagingSenderId: '605845063930',
    projectId: 'luxe-ecom-a5022',
    storageBucket: 'luxe-ecom-a5022.firebasestorage.app',
    iosBundleId: 'com.wonderkids.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGxV5YtIlTU29t9d-XgqaCZB8km8mIf7U',
    appId: '1:605845063930:ios:55ce97a10a9d9e2d316143',
    messagingSenderId: '605845063930',
    projectId: 'luxe-ecom-a5022',
    storageBucket: 'luxe-ecom-a5022.firebasestorage.app',
    iosBundleId: 'com.wonderkids.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJY_ONMjam_W6Yofc76KnI2j_BQwZ5Zuo',
    appId: '1:605845063930:web:febe0653cf1aa3e5316143',
    messagingSenderId: '605845063930',
    projectId: 'luxe-ecom-a5022',
    authDomain: 'luxe-ecom-a5022.firebaseapp.com',
    storageBucket: 'luxe-ecom-a5022.firebasestorage.app',
  );
}
